### PR TITLE
Updated Windows Instructions

### LINKED ISSUE #22: Update instructions environment setup on Windows
I would like to update the Windows section of [Environment set up](https://acrf-image-x-institute.github.io/packaging_demo/set_up_environment.html#windows). It seems Windows can be a bit tricky/non-intuitive regarding the availability of Python in the command line or PowerShell, especially since some installation methods don't automatically add the interpreter to PATH. I would like to add a small section on how to access `python.exe`, if it's not available.

### PR DESCRIPTION
**Pull request by lmejn**
Updated the instructions for setting up the environment on Windows, including a small section on troubleshooting Windows issues.

Closes #22

### CODE REVIEW

**Review by bwheelz36 — COMMENTED** [review]
Thanks!

- where you have all the locations python might be, maybe add this:

> :information_source: typing `%APPDATA%` in windows explorer will take you to `C:\Users\<username>\AppData\Local\`

- also in my experience, the most likely place for python to go when it is installed as a standalone program is `C:\Users\<username>\AppData\Local\Programs\` so maybe reverse the order of this list?

**Comment by bwheelz36** [comment]
also the info about adding to path is quite helpful, thanks :-) do you know how different versions would be handled? will e.g. python3.10 be added as python or python3 or python3.10? and can I control this?

**Comment by bwheelz36** [comment]
oh I didn't realise I can make changes when I review! cool!

**Comment by lmejn** [comment]
I just checked `%APPDATA%`, but for me it only works in file explorer and cmd, but not PowerShell (why windows, why!). I'd suggest to keep it as is.

I've re-ordered the list of likely locations. I've also expanded on adding `pip.exe` to `PATH` as this seems to be in a subfolder where python is located. Without adding this to `PATH`, you can't run the `pip` command.

**Comment by lmejn** [comment]
> also the info about adding to path is quite helpful, thanks :-) do you know how different versions would be handled? will e.g. python3.10 be added as python or python3 or python3.10? and can I control this?

Adding python to `PATH` manually complicates having different versions of python, mainly due to the official python installer. To get technical, how it works on linux, when you install a version of python (say 3.9) to the system (*e.g.* using `apt`), is that it creates an executable called `python3.9`, then symlinks `python` to `python3.9`. So calling `python` essentially calls the executable `python3.9`. When installing a new version of python (say 3.10), it creates `python3.10` and symlinks `python` to `python3.10`, but importantly `python3.9` still available. Hence you have two versions of python available: `python` (which is actually `python3.10`) and `python3.9`.

The official python installer on Windows doesn't seem to add these version numbers to their python executables, so installing 3.9 and 3.10 will create two separate `python.exe`, albeit in different folders. even adding both of these to `PATH` won't give you the same two version functionality. I'm sure an IDE like PyCharm knows how to handle this.

This seems to be a limitation of the official python installer. Interestingly installing python through the Microsoft Store does add version numbers to the executables, allowing multiple versions, and it is already added to `PATH`.

**Comment by lmejn** [comment]
Having a look at the docs, the official python installer wants you to use their [Python Launcher for Windows](https://docs.python.org/3/using/windows.html#launcher), so this is another option.

I believe the only difference is the command for setting up the venv: `py -m venv new_venv`

**Comment by bwheelz36** [comment]
> (why windows, why!). 

If I had a dollar for every time...
Ok thanks!

**Pull request merged**
